export const ADD_INGREDENT = 'ADD_INGREDENT'
export const REMOVE_INGREDENT = 'REMOVE_INGREDENT'
export const INIT_INGREDENTS = 'INIT_INGREDENTS'

export const FETCH_ORDERS = 'FETCH_ORDERS'

export const AUTHENTICATION = 'AUTHENTICATION'
export const AUTH_FAIL = 'AUTH_FAIL'
export const LOGOUT = 'LOGOUT'
export const SET_AUTH_REDICRECT_PATH = 'SET_AUTH_REDICRECT_PATH'